env:
  global:
    - secure: cmOvzJJcqhNk9XmJ6gsBVFlrUV4FiOPzRzzDkOnEq9d2vIxf9dtM9871R3dX9w/E1Zckj9RduQPs6CR403CtOsX6EAi7WSwuJOeDfhRzIZ7Dw3MO++C+XaBPkOoBZqXwAue4Kj00H/d4TvzorhAvteN5q6c7P/ht7UzUY4YUywU=
language: rust
before_install:
    - sudo apt-get update
    - sudo apt-get install xorg-dev
after_script:
    - cargo doc
    - mv target/doc .
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
